export const PROVINCES_TEXT = {
  bsas: 'Buenos Aires',
  catamarca: 'Catamarca',
  chaco: 'Chaco',
  chubut: 'Chubut',
  caba: 'Ciudad Autonoma de Buenos Aires',
  cba: 'Cordoba',
  corrientes: 'Corrientes',
  entre_rios: 'Entre Rios',
  formosa: 'Formosa',
  jujuy: 'Jujuy',
  la_pampa: 'La Pampa',
  la_rioja: 'La Rioja',
  mendoza: 'Mendoza',
  misiones: 'Misiones',
  neuquen: 'Neuquen',
  rio_negro: 'Rio Negro',
  salta: 'Salta',
  san_juan: 'San Juan',
  san_luis: 'San Luis',
  santa_cruz: 'Santa Cruz',
  santa_fe: 'Santa Fe',
  santigo_del_estero: 'Santigo del Estero',
  tierra_del_fuego: 'Tierra del Fuego, Antartida e Islas del Atlantico Sur',
  tucuman: 'Tucuman',
} as const

export const PROVINCES_ID = {
  bsas: 'buenos-aires',
  catamarca: 'catamarca',
  chaco: 'chaco',
  chubut: 'chubut',
  caba: 'caba',
  cba: 'cordoba',
  corrientes: 'corrientes',
  entre_rios: 'entre-rios',
  formosa: 'formosa',
  jujuy: 'jujuy',
  la_pampa: 'la-pampa',
  la_rioja: 'la-rioja',
  mendoza: 'mendoza',
  misiones: 'misiones',
  neuquen: 'neuquen',
  rio_negro: 'rio-negro',
  salta: 'salta',
  san_juan: 'san-juan',
  san_luis: 'san-luis',
  santa_cruz: 'santa-cruz',
  santa_fe: 'santa-fe',
  santigo_del_estero: 'santigo-del-estero',
  tierra_del_fuego: 'tierra-del-fuego',
  tucuman: 'tucuman',
} as const

export const MONTH_ID = {
  enero: 'enero',
  febrero: 'febrero',
  marzo: 'marzo',
  abril: 'abril',
  mayo: 'mayo',
  junio: 'junio',
  julio: 'julio',
  agosto: 'agosto',
  septiembre: 'septiembre',
  octubre: 'octubre',
  noviembre: 'noviembre',
  diciembre: 'diciembre',
} as const

export const MONTH_TEXT_ES = {
  Enero: 'Enero',
  Febrero: 'Febrero',
  Marzo: 'Marzo',
  Abril: 'Abril',
  Mayo: 'Mayo',
  Junio: 'Junio',
  Julio: 'Julio',
  Agosto: 'Agosto',
  Septiembre: 'Septiembre',
  Octubre: 'Octubre',
  Noviembre: 'Noviembre',
  Diciembre: 'Diciembre',
} as const

export const MONTH_TEXT_EN = {
  Enero: 'January',
  Febrero: 'February',
  Marzo: 'March',
  Abril: 'April',
  Mayo: 'May',
  Junio: 'June',
  Julio: 'July',
  Agosto: 'August',
  Septiembre: 'September',
  Octubre: 'October',
  Noviembre: 'November',
  Diciembre: 'December',
} as const

export const MONTH_TEXT_FR = {
  Enero: 'Janvier',
  Febrero: 'Février',
  Marzo: 'Mars',
  Abril: 'Avril',
  Mayo: 'Peut',
  Junio: 'Juin',
  Julio: 'Juillet',
  Agosto: 'Août',
  Septiembre: 'Septembre',
  Octubre: 'Octobre',
  Noviembre: 'Octobre',
  Diciembre: 'Décembre',
} as const
